"""Generate CODEMAP.md: where everything lives, so a task starts at the right file.

Run from the repo root:  python -m src.packet_tracer_mcp.devtools.codemap
The module table is kept by hand below; the tool index is read from the live
registry, so it cannot drift. tests/test_codemap.py fails when the file is stale.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

# Path (relative to src/packet_tracer_mcp/) -> what it owns.
MODULES: dict[str, str] = {
    "server.py": "FastMCP app: registers tools, resources, prompts",
    "settings.py": "SERVER_INSTRUCTIONS (<2 KB, sent to every client) and GUIDE (served as pt://guide)",
    "adapters/mcp/tool_registry.py": "register_tools(): runs every tools/<topic>.register in TOOL_MODULES order",
    "adapters/mcp/bridge_context.py": "BridgeContext: HTTP/file channel pick, send, send_and_wait, live_devices",
    "adapters/mcp/tools/": "one module per topic, each register(mcp, ctx); tool index below",
    "adapters/mcp/device_panel_tools.py": "device-window tools: CLI, Command Prompt, IP config, UI mode",
    "adapters/mcp/desktop_service_tools.py": "Desktop apps and Server-PT services tools",
    "adapters/mcp/panel_support.py": "PanelSupport: call PT, show/capture windows for panel tools",
    "adapters/mcp/resource_registry.py": "MCP resources: catalogs, capabilities, pt://guide",
    "adapters/mcp/prompt_registry.py": "MCP prompts (ui_on, ui_off, ui_status)",
    "application/use_cases/": "use cases: rules + generators, dependencies injected",
    "domain/models/": "Pydantic models (no validation inside)",
    "domain/rules/": "validation rules returning ValidationResult",
    "domain/services/": "planning, IP plan, estimator, explainer, diff, audit, packet trace",
    "infrastructure/catalog/": "device, cable, module, alias and template catalogs",
    "infrastructure/execution/": "live HTTP bridge, file bridge, token, console session engine",
    "infrastructure/generator/": "PTBuilder JS and IOS CLI generators (json.dumps for every JS field)",
    "infrastructure/persistence/": "project repository (save/load plans)",
    "infrastructure/platform/": "OS facts: state dir, mailbox candidates, clipboard, output root, host",
    "infrastructure/platform/doctor.py": "read-only doctor CLI, client config and platform/UI diagnostics",
    "infrastructure/ui/": "UI mode: OS-agnostic presenter, WindowBackend seam (backend.py), widget locators",
    "infrastructure/ui/backends/": "load_backend(): Windows Win32/UI Automation, macOS AX/capture, Linux null; lazy OS imports",
    "shared/": "constants, enums, ui_mode store, utils (safe paths, js_escape, to_json, reply_json)",
    "devtools/codemap.py": "this generator",
    "devtools/live_smoke.py": "runs tests/live/*.json tool calls from this checkout against a live PT",
    "devtools/macos_probe.py": "macOS probe: TCC permissions, CG/AX windows, AX tree fixtures, click and capture routes",
}

HEADER = """# CODEMAP

Generated by `python -m src.packet_tracer_mcp.devtools.codemap`; do not edit by hand
(`tests/test_codemap.py` fails when it is stale). Paths are relative to `src/packet_tracer_mcp/`.
To find a tool: search this file for its name, then open that file and search `def <tool>(`.
"""


def _tool_files() -> dict[str, list[str]]:
    from ..server import mcp

    files: dict[str, list[str]] = defaultdict(list)
    for tool in mcp._tool_manager.list_tools():
        module = tool.fn.__module__.removeprefix("src.").removeprefix("packet_tracer_mcp.")
        files[module.replace(".", "/") + ".py"].append(tool.name)
    return files


def render() -> str:
    lines = [HEADER, "## Modules", "", "| Path | Owns |", "|---|---|"]
    lines += [f"| `{path}` | {owns} |" for path, owns in MODULES.items()]
    lines += ["", "## Tools by file", "", "| File | Tools |", "|---|---|"]
    for path, tools in sorted(_tool_files().items()):
        lines.append(f"| `{path}` | {', '.join(sorted(tools))} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    Path("CODEMAP.md").write_text(render(), encoding="utf-8", newline="")
    print("CODEMAP.md written")
